backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

display_url: https://patrick-laing-gatsby.netlify.com/

collections:
  - name: "main"
    label: "Main"
    file: "src/pages/index.md"
    fields:
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "navbar" }
      - {
          label: "SEO",
          name: "seo",
          widget: "object",
          fields:
            [
              { label: "Title", name: "title", widget: "string" },
              { label: "Description", name: "description", widget: "string" },
              { label: Share Image, name: shareImage, widget: image }
            ]
        }
      - {
        label: "Sections",
        name: "sections",
        widget: "object",
        fields:
          [
            {
              label: "Left",
              name: "left",
              widget: "object",
              fields:
                [
                  { label: "Title", name: "title", widget: "string" },
                  { label: Image, name: image, widget: image }
                  { label: Video, name: video, widget: file }
                ]
            },
            {
              label: "Right",
              name: "right",
              widget: "object",
              fields:
                [
                  { label: "Title", name: "title", widget: "string" },
                  { label: Image, name: image, widget: image }
                  { label: Video, name: video, widget: file }
                ]
            }
          ]
      }
      - {
          label: "Contact",
          name: "contact",
          widget: "object",
          fields:
            [
              { label: "linkText", name: "label", widget: "string" },
              { label: "Email Address", name: "emailAddress", widget: "string" },
            ]
        }
      - {
          label: "Credits",
          name: "credits",
          widget: "list",
          fields:
            [
              { label: Text, name: linkText, widget: string },
              { label: URL, name: linkURL, widget: string },
            ]
        }
